version: '3.8'

services:
  db:
    image: postgres:14-alpine
    container_name: agendamento_db
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=agendamento_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

 
  api:
    container_name: agendamento_api
    build:
      context: ./api
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./api:/app
    environment:
      - DATABASE_URL=postgresql://admin:admin@db:5432/agendamento_db
      - BROKER_URL=amqp://guest:guest@broker:5672/
    depends_on:
      - db
      - broker

  
  broker:
    image: rabbitmq:3.10-management-alpine
    container_name: agendamento_broker
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest

volumes:
  pgdata: